### ISSUE TITLE
cannot update to version 1.2.0

### ISSUE THREAD

**Issue by ppham27** [thlorenz/brace#35]
I tried to run the script to update to version 1.2.0 of the Ace Editor. I get a `JS_Parse_Error` when trying to minify the `workersrc/coffee.js`.

```
$ node --stack-trace-limit=1000 build/update.js 
Cloning into '/Users/phil/tmp/brace/build/ace-build'...
Already up-to-date.
Note: checking out 'v1.2.0'.

...

/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:204
    throw new JS_Parse_Error(message, filename, line, col, pos);
          ^
Error
    at new JS_Parse_Error (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:204:11)
    at croak (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:684:41)
    at token_error (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:688:9)
    at expect_token (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:701:9)
    at expect (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:704:36)
    at function_ (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:964:9)
    at /Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:815:24
    at /Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:727:24
    at block_ (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1007:20)
    at /Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:980:25
    at function_ (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:985:15)
    at expr_atom (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1193:24)
    at maybe_unary (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1363:19)
    at expr_ops (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1398:24)
    at maybe_conditional (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1403:20)
    at maybe_assign (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1427:20)
    at expression (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1446:20)
    at expr_list (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1212:24)
    at subscripts (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1346:30)
    at subscripts (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1323:20)
    at expr_atom (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1199:20)
    at maybe_unary (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1363:19)
    at expr_ops (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1398:24)
    at maybe_conditional (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1403:20)
    at maybe_assign (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1427:20)
    at expression (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1446:20)
    at simple_statement (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:894:55)
    at /Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:767:19
    at /Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:727:24
    at /Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1474:23
    at Object.parse (/Users/phil/tmp/brace/node_modules/uglify-js/lib/parse.js:1484:7)
    at minify (/Users/phil/tmp/brace/build/stringify-workers.js:12:20)
    at /Users/phil/tmp/brace/build/stringify-workers.js:27:40
    at Array.forEach (native)
    at module.exports (/Users/phil/tmp/brace/build/stringify-workers.js:21:6)
    at workers (/Users/phil/tmp/brace/build/update.js:155:3)
    at Object.<anonymous> (/Users/phil/tmp/brace/build/update.js:156:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by thlorenz** [comment]
We upgraded successfully to 1.2.2 now, so closing this
