### ISSUE TITLE
Warning thrown in Electron project

### ISSUE THREAD

**Issue by fritz-c** [thlorenz/brace#54]
I'm using brace in an electron project, and it throws a warning every time it's run:

```
/my/project/path/node_modules/brace/index.js:3543
Could not load worker TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at TypeError (native)
    at new WorkerClient (/my/project/path/node_modules/brace/index.js:16410:52)
    at createWorker (/my/project/path/node_modules/brace/mode/svg.js:643:22)
    at $startWorker (/my/project/path/node_modules/brace/index.js:8762:39)
    at $onChangeMode (/my/project/path/node_modules/brace/index.js:8718:18)
    at .<anonymous> (/my/project/path/node_modules/brace/index.js:8699:22)
    at exports.loadModule (/my/project/path/node_modules/brace/index.js:3695:26)
    at setMode (/my/project/path/node_modules/brace/index.js:8688:16)
    at HTMLDocument.<anonymous> (/my/project/path/lib/scripts/main.js:98:25)
    at i (/my/project/path/vendor/jquery.min.js:2:27451)
```

The line it's pointing at is https://github.com/thlorenz/brace/blob/master/index.js#L16410

``` js
var blobUrl = (window.URL || window.webkitURL).createObjectURL(blob);
```

I'm assuming there's an issue with the window object in electron.

**Comment by farfromrefug** [comment]
That's because of this line.
https://github.com/thlorenz/brace/blob/master/index.js#L16408
If you comment it it will work perfectly.

Could this require be made only if necessary?

Thanks

**Comment by thlorenz** [comment]
That would need to be fixed in Ace, please file there.

**Comment by simonhochrein** [comment]
Same Problem

**Comment by thlorenz** [comment]
@simonhochrein as I said, needs to be fixed in Ace, so adding more comments here isn't helping anyone ;)
