### ISSUE TITLE
php worker does not work

### ISSUE THREAD

**Issue by mokevnin** [thlorenz/brace#55]
```
Could not load worker TypeError: Cannot read property 'split' of undefined
    at exports.moduleUrl (eval at <anonymous> (http://localhost:9000/assets/main.js:1:0), <anonymous>:3657:21)
    at new WorkerClient (eval at <anonymous> (http://localhost:9000/assets/main.js:1:0), <anonymous>:16395:41)
    at createWorker (eval at <anonymous> (http://localhost:9000/assets/main.js:1:0), <anonymous>:13307:22)
    at $startWorker (eval at <anonymous> (http://localhost:9000/assets/main.js:1:0), <anonymous>:8762:39)
    at $onChangeMode (eval at <anonymous> (http://localhost:9000/assets/main.js:1:0), <anonymous>:8718:18)
    at eval (eval at <anonymous> (http://localhost:9000/assets/main.js:1:0), <anonymous>:8699:22)
    at exports.loadModule (eval at <anonymous> (http://localhost:9000/assets/main.js:1:0), <anonymous>:3695:26)
    at setMode (eval at <anonymous> (http://localhost:9000/assets/main.js:1:0), <anonymous>:8688:16)
    at Editor.componentDidMount (eval at <anonymous> (http://localhost:9000/assets/main.js:1:0), <anonymous>:75:15)
    at CallbackQueue._assign.notifyAll (eval at <anonymous> (http://localhost:9000/assets/main.js:1:0), <anonymous>:66:22)
```

**Comment by hellpf** [comment]
The same is with xquery-worker. Please remove it from mode/xquery.js or create an empty worker.

**Comment by pankitgami** [comment]
@thlorenz Is there any solution for this? I am also stuck with this.

**Comment by thlorenz** [comment]
Nope, I wasn't able to properly convert those workers into blobs .. tried for a while, but they don't properly stringify.
However anyone is welcome to try and fix this I'd be very happy with a PR that does :)

**Comment by beryllium** [comment]
If I replace the reference to `mod.id` in `index.js` near line 18003 with just `mod`, the error goes away and the code seems to be highlighted. Could the fix be this simple, or am I missing something?

**Comment by ozws** [comment]
@beryllium, thanks, that worked for getting rid of the warning.

However, I needed the following to get the highlighting working (from [#2542 (comment)](https://github.com/ajaxorg/ace/issues/2542#issuecomment-111288259)):

```
session.setMode({path:"ace/mode/php", inline:true})
```

**Comment by ajthinking** [comment]
Good catch @beryllium and @ozws, thank you! If it need to keep working for other languages alongside php, set line ~18003 to

```
workerUrl = workerUrl || config.moduleUrl(mod.id ? mod.id : mod, "worker");
```

I put the whole thing in a new file `BraceWithBugFix.js` and then used `var ace = require('./BraceWithBugFix');` feels somewhat dirty though :smile:
